### ISSUE TITLE
Some results of uci regression seems too good to believe

### ISSUE THREAD

**Issue by rtz19970824** [ICL-SML/Doubly-Stochastic-DGP#18]
Hi there,

I directly ran your code in [demo_regression_UCI.ipynb](https://github.com/ICL-SML/Doubly-Stochastic-DGP/blob/master/demos/demo_regression_UCI.ipynb) with Boston housing and protein data and got an RMSE of ~1.9 and ~2.0 respectively. It's too good to believe as I never heard someone can reach a result like that before. It's also far away from your report in NIPS paper. Can you have a check?

Thanks,

**Comment by hughsalimbeni** [comment]
For boston I think 1.9 is possible for a single split (there's quite a variation as there are only 506 points). What do you get for the single layer models? 

For protein there's an error in the data file. It was taking the last column rather than the first. Thanks for spotting this. We used hand-curated files for the results in the paper, rather than these rather hastily cobbled together scripts. Also I notice that energy was taking the last column, but usually it's the penultimate column that people used. I've updated that also.

**Comment by hughsalimbeni** [comment]
Could you confirm that the results seem sensible to you? If you spot any other data processing error do let me know!

**Comment by hughsalimbeni** [comment]
Thanks for checking these out. I'll merge the PR now. 

Regarding mnist, the notebook reports

sgp test lik: -0.1092, test acc 0.9698
dgp2 test lik: -0.0731, test acc 0.9794
dgp3 test lik: -0.0709, test acc 0.9799

and the paper reports sgp 97.48%, dgp2 98.06% and dgp3 98.11% . The difference in implementations are the batchsize (10K in the paper rather than 1K in the notebook), and the number of iterations (100K in the paper instead of 20K in the notebook), so I'd expect all the numbers to be slightly lower in the notebook than the paper. It's interesting that the single layer model is relatively worse off with the reduced batch size and reduced training. Perhaps the DGP optimization is easier in some sense. It's hard to tell with stochastic non-convex optimization. 

One other small point is that the version of gpflow that ran the experiments used without-replacement minibatch batches, whereas the new gpflow uses tensorflow minibatches, which are much faster but sample with replacement so there will likely be repeats in the batch, especially with large batches relative to the size of the dataset. This might influence training in a non-obvious way, especially for the single layer model where there isn't any randomness to separate identical examples.
