### ISSUE TITLE
Question of size of minibatch and input space.

### ISSUE THREAD

**Issue by hoangcuong2011** [ICL-SML/Doubly-Stochastic-DGP#4]
Hi,

I noticed that the size of minibatch is crucial to the performance.

If I let the size as 10.000 as you recommend, DGPs would work quite well. Meanwhile, if I use much smaller minibatch size (e.g. 128), the final performance would be pretty bad in general.
Do you have any intuition why it is the case?

I also noticed that your framework does not work well with high-dimensional inputs (e.g. 17). What I mean not so well is that deeper models do not help much. Do you think this is true? Did you ever observe any significant improvements by using deep models for a regression task with such an high-dimensional input space?

Thanks,

Best,

**Comment by hughsalimbeni** [comment]
Hi thanks for your interest in the code!

You should be able to use small batches, but you'll have to set the Adam learning rate down e.g. use 1e-4 and take loads of steps. In the paper we found that large batches uses the GPU more efficiently, so we went for large batch and large learning rate. I haven't experimented much with small batches, but I know stability with Adam(0.01) is an issue, even for a single layer model with some datasets. In the noise-free case Adam(0.01) is pretty good in all cases I've tried, but not when using small batches. It depends on lots of factors like the influence of tail datapoints (e.g. in MNIST only a few ambiguous digits make a difference late on in optimization, so small batches give you high variance updates), the condition number of q_sqrt (ill-conditioning makes everything less stable), and how you've parameterized the model e.g. using precision instead of variance or 1/lengthscale instead of lengthscale can make a big difference to stability. 

Regarding high dim inputs, are you performing some sort of dim reduction, or using different datasets? It could be that the high dim dataset has less structure that additional layers can exploit, or it may be that for high dim data you need to init with a longer lengthscale for the inner layers (otherwise everything might be too far apart to do anything interesting). Also, have you tried reducing down e.g. 17, 5, 5, or are you using 17, 17, 17?
