### ISSUE TITLE
Internal representation of q_mu and q_sqrt

### ISSUE THREAD

**Issue by pablomorales92** [ICL-SML/Doubly-Stochastic-DGP#40]
Hi, 

I am trying to understand the correspondence between the variables `q_mu`/`q_sqrt` in the `SVGP_Layer` class and the $m_l$/$S_l$ variables in the NIPS 2017 paper. My current understanding is that this depends on the `white` flag (i.e. whitening the representation of the GP) as follows:

If `white=False`, then S_l = q_sqrt*q_sqrt^T and m_l=q_mu+mean_function(Z^{l-1}). [Z^{l-1} are the inducing point locations for that layer]. Side note: although `white=False`, the mean m_l does not coincide with q_mu (which I would have expected, but well, I think this is just a matter of what each one understands for "(not) whitening").

If `white=True`, then S_l= A*(q_sqrt*q_sqrt^T)\*A^T  and m_l = A\*q_mu+mean_function(Z^{l-1}). Here, A is the cholesky decomposition of K(Z^{l-1}) [the kernel matrix at the inducing points].

My questions are: 
1) Is this understanding correct?
2) What's the rationale behind the inclusion of a `white` flag? I mean, I see no point about letting the user choose the internal representation of variables... that should be sth "transparent" for him/her. 
3) If my understanding is correct, `q_mu` and `q_sqrt` represent different things depending on the `white` flag. Would it make sense to include methods `get_m` and `get_S` for the `SVGP_Layer` class which return the value of the paper variables `m_l` and `S_l` (regardless of their internal representation)? I think this would be useful for a user who has read the paper and wants to play around with the code without diving into the details of the implementation.

Thanks a lot, and great job! :)

**Comment by hughsalimbeni** [comment]
You ask good questions. 

1. Yes, your understanding is correct. 

2. The reason the option is there in SVGP (and then in the DGP code also), is that it isn't actually totally obvious which is better. The reason white is the default is probably because it's computationally easier (only one matrix solve rather than two, and the KL is faster) and because the whitened version appears to works better in some simple cases, especially in 1D. Another more trivial reason is that it doesn't require to calculate anything for the initialization (if white=False then using the identity for the q_sqrt init isn't probably a good idea). But in general there is no reason why it should be better than the unwhitened version in all situations. 

3. Yes you're absolutely right. It might be a nice idea to have a helper function to get the data-space values, though in practice when I want them I just call `predict_f_full_cov(Z)`, as that is the same (up to jitter, and assuming there isn't any white noise on the kernel).

If you look at the more recent code https://github.com/hughsalimbeni/DGPs_with_IWVI you'll see that I've hard-coded white=True, mainly because it's simpler to implement. 

On final point: natural gradients have the nice property of being invariant to linear transformation, so in that case it makes no difference at all.

**Comment by pablomorales92** [comment]
Thanks a lot for the detailed reply, I close this! 👏
